name: Reusable workflow to release literate-octo-umbrella

on:
  workflow_call:
    inputs:
      git-tag:
        description: Git tag to release
        type: string
        required: true
      python-version:
        type: string
        required: true

jobs:
  make-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ inputs.git-tag }}
        fetch-depth: 0
    - name: List files
      run: |
        Get-ChildItem .
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        # cache: pip
        # cache-dependency-path: |
        #   pyproject.toml
    - name: Python full version
      id: python-full
      run: |
        python --version | ForEach-Object { 'version=' + ($_.Trim() -split '\s+')[1] } >> $Env:GITHUB_OUTPUT
    - name: Recall Python version ${{ steps.python-full.outputs.version }}
      run: echo ${{ steps.python-full.outputs.version }}
    - name: Build literate-octo-umbrella
      run: |
        python -m pip install build
        python -m build
    - name: Release version ${{ inputs.git-tag }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.git-tag }}
        body: |
          \## Changes
          See the [README](https://github.com/suvayu/literate-octo-umbrella/blob/${{ inputs.git-tag }}/README.md)
        files: |
          dist/*.whl
